name: CI/CD Pipeline for User Management Microservice

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the Node.js version your app requires

      # Install dependencies Server1
      - name: Install dependencies
        run: |
          cd Server1
          npm install
        working-directory: ./Server1

        # Install dependencies Server2
      - name: Install dependencies
        run: |
          cd Server2
          npm install
        working-directory: ./Server2

      # Build Docker image with MONGO_URI and JWT_SECRET as build arguments
      - name: Build Docker image
        run: |
          docker build --build-arg MONGO_URI=${{ secrets.MONGO_URI }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} -t my-node-app .

       # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
         echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin docker.io
         docker tag my-node-app $DOCKER_USERNAME/nodeapp:latest  # Tag with your Docker Hub username
         docker push $DOCKER_USERNAME/nodeapp:latest            # Push the image to your Docker Hub repository
        env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
